### PR TITLE
added some spanish ymls

### PR DESCRIPTION
**Pull request by Henderjay**
added a few spanish ymls, and added Shewen in English.

### CODE REVIEW

**Comment by jaredh159** [comment]
@Henderjay -- you've got a failing test here.  If you run `yarn test` you'll see it.  Basically, the spanish Penington has a _format_ of audio, but no audio data, which is not allowed.  So, you should just remove the audio format for now until we get the data ready. That should get the tests passing, and probably might sort out the `phipps:compare` error as well. 👍

**Comment by Henderjay** [comment]
So should I make that change and send it as a new pr?  Or amend the
branch?

**Comment by jaredh159** [comment]
just do it right on this branch and force push after you amend.

**Comment by Henderjay** [comment]
Ok, I did it. And you were right, that fixed phipps compare.

**Pull request merged**
